apiVersion: v2
appVersion: 1.5.0
description: A Helm chart for deploying Text Embeddings Inference(TEI) from Hugging
  Face
keywords:
- tei
- text-embeddings-inference
- embeddings
- huggingface
- rag
name: text-embeddings-inference
sources:
- https://github.com/huggingface/text-embeddings-inference
type: application
version: 0.1.7
