{{- if .Values.horizontalPodAutoscaler.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "tgi.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "tgi.fullname" . }}
  minReplicas: 1
  maxReplicas: {{ .Values.horizontalPodAutoscaler.maxReplicas }}
  metrics:
  - type: Object
    object:
      metric:
        name: {{ include "tgi.metricPrefix" . }}_request_latency
      describedObject:
        apiVersion: v1
        kind: Service
        name: {{ include "tgi.fullname" . }}
      target:
        type: Value
        value: 4
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 180
      policies:
      - type: Percent
        value: 25
        periodSeconds: 90
    scaleUp:
      selectPolicy: Max
      stabilizationWindowSeconds: 0
      policies:
      - type: Pods
        value: 1
        periodSeconds: 90
{{- end }}
