[project]
name = "ra-search"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "transformers",
    "huggingface-hub==0.25.0",
    "gradio==4.44.0"
]